# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Axe CI
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  unittest:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci --legacy-peer-deps
      - name: Unit tests with vitest-axe
        run: npm run test -- run
  axe-cli:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci --legacy-peer-deps
      - name: Unit tests with vitest-axe
        run: npm run build
      - run: npm run preview & npx wait-on http://localhost:5173
      - name: Axe CLI against running prod build
        run: npm run axe -- --exit
      - name: Read Axe output file.
        id: axe_output
        uses: juliangruber/read-file-action@v1
        with:
          path: ./axe-results.json
      - uses: actions/upload-artifact@v3
        with:
          name: axe-results
          path: axe-results.json
      - name: Comment on pull request.
        uses: thollander/actions-comment-pull-request@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          message: "<details><summary>Axe testing results</summary>



```${{ steps.axe_output.outputs.content }}```

</details>"
  e2e:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci --legacy-peer-deps
      - name: Unit tests with vitest-axe
        run: npm run build
      - run: npm run preview & npx wait-on http://localhost:5173
      - name: Cypress E2e against running prod build
        run: npm run cy:run
